### ISSUE TITLE
Missing red

### ISSUE THREAD

**Issue by kohlsalem** [dotsam/homebridge-milight#7]
Hi again,

beside the question, why someone would set his light to "red", i noticed, that it is not possible via siri voice command.

Reading the source the root cause becomes obvious. However, is it really correct to determine white mode on the hue=0?

Should'nt it be saturation=0, while every saturation >0 returns to last hue?

Best
Michael

**Comment by dotsam** [comment]
Hi Michael,

That part of the code was rather hastily thrown together as I was figuring out how different apps set hue and saturation differently when one property or the other wasn't present. Since these calls are sent separately, I'll probably have to take another look at this and check the current value of the saturation when doing anything based on the hue that is being set.

**Comment by NewFolk** [comment]
Hello, is there any update about red support with Siri ?

**Comment by dotsam** [comment]
Fixed in 0dbe67abc17ac0f26237c1a792b32d8ea85175db
